apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: mctc-demo
spec:
  hostnames:
  - "m2demo.apps.davemartin.io"
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: example-gateway
    namespace: mctc-downstream
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: mctc-demo
      port: 80
      weight: 1
    matches:
    - method: GET
      path:
        type: PathPrefix
        value: /
